class DoctorSummary:
    def generate(self, report: dict, insights_data: dict) -> str:
        """
        Generates readable text summary for doctors including
        total days, symptoms, duration, insights, and risk level.
        
        Args:
            report (dict): Generated by ReportBuilder.build().
            insights_data (dict): Generated by InsightGenerator.generate().
            
        Returns:
            str: A formatted readable text summary.
        """
        total_days = report.get("total_days", 0)
        max_duration = report.get("max_duration", 0)
        symptoms_freq = report.get("symptom_frequency", {})
        
        symptoms_parts = []
        for s, f in symptoms_freq.items():
            symptoms_parts.append(f"{s} ({f} time{'s' if f > 1 else ''})")
        
        symptoms_str = ", ".join(symptoms_parts)
        if not symptoms_str:
            symptoms_str = "None logged"
            
        risk_level = insights_data.get("risk_level", "Unknown")
        insights_list = insights_data.get("insights", [])
        insights_str = "\n  - ".join(insights_list) if insights_list else "None"
        
        summary = []
        summary.append( "=== WEEKLY PATIENT REPORT ===")
        summary.append(f"Total Logs/Days Tracked: {total_days}")
        summary.append(f"Maximum Symptom Duration: {max_duration} day(s)")
        summary.append(f"Symptoms Reported: {symptoms_str}")
        summary.append( "")
        summary.append( "--- INSIGHTS & RISK ---")
        summary.append(f"Risk Level: {risk_level}")
        summary.append(f"Observations:\n  - {insights_str}")
        summary.append( "===============================")
        
        return "\n".join(summary)
