class InsightGenerator:
    def generate(self, report: dict) -> dict:
        """
        Detects persistent symptoms (>=3 days) and classifies risk.
        Logic:
        - Low (<3 days)
        - Moderate (3-4 days)
        - High (>=5 days)
        
        Args:
            report (dict): Generated by ReportBuilder.build().
            
        Returns:
            dict: Recommended insights and assigned risk level.
        """
        max_duration = report.get("max_duration", 0)
        symptom_freq = report.get("symptom_frequency", {})
        
        insights = []
        
        # Detect persistent symptoms (those appearing >= 3 times in logs or based on duration)
        persistent_symptoms = [s for s, freq in symptom_freq.items() if freq >= 3]
        
        # If no symptom logged 3+ times, but one was noted to last >=3 days
        if max_duration >= 3 and not persistent_symptoms:
            persistent_symptoms = list(symptom_freq.keys())
            
        if persistent_symptoms:
            insights.append(f"Persistent symptoms detected: {', '.join(persistent_symptoms)}")
        else:
            insights.append("No persistent symptoms logged.")
            
        # Classify risk
        if max_duration >= 5:
            risk_level = "High"
            insights.append("Symptoms lasting 5+ days. Immediate follow-up required.")
        elif max_duration >= 3:
            risk_level = "Moderate"
            insights.append("Symptoms ongoing for 3-4 days. Monitor patient closely.")
        else:
            risk_level = "Low"
            insights.append("Symptoms recent (<3 days). Routine care recommended.")
            
        return {
            "insights": insights,
            "risk_level": risk_level
        }
